"use server";

import { createClient } from "@/utils/supabase/server";
import { generateSystemPrompt } from "@services/agentService";
import { ChildInfoAPI } from "@/types/agents";

export async function addChild(formData: FormData) {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { error: "Usuario no autenticado", success: false };
  }

  const nombre = formData.get("nombre") as string;
  const edadString = formData.get("edad") as string; // Keep as string for prompt
  const curso = formData.get("curso") as string;
  const gustos = formData.get("gustos") as string;
  const comunidadAutonoma = formData.get("comunidadAutonoma") as string;
  const observaciones = formData.get("observaciones") as string;
  // TODO: Add avatar upload logic if needed, for now use a default or empty

  const systemPrompt = generateSystemPrompt({
    nombre,
    edad: edadString,
    curso,
    gustos,
    comunidadAutonoma,
    observaciones,
  });

  if (!nombre || !edadString) {
    return { error: "Nombre y edad son obligatorios", success: false };
  }

  // 1. Prepare new child object for 'hijos' table
  // Using Omit to exclude 'id' which is generated by the DB
  const newChild: Omit<ChildInfoAPI, "id"> = {
    nombre,
    edad: parseInt(edadString, 10), // Parse to number for DB
    curso,
    gustos,
    observaciones,
    system_prompt: systemPrompt,
    comunidad_autonoma: comunidadAutonoma,
    perfil_id: user.id, // Foreign key to perfiles table
  };

  // 2. Insert new child into 'hijos' table
  const { error: insertError } = await supabase
    .from("hijos")
    .insert([newChild]);

  if (insertError) {
    console.error("Error inserting child:", insertError);
    return { error: "Error al añadir el perfil del niño/a", success: false };
  }

  return { success: true };
}
